name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd apps && npm install
    - run: cd apps && npm run build:startup
    - run: cd apps && npm run test:startup
      env:
        CI: true
