name: Nonogramm build & lint & test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 7
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd apps && npm install
    - run: cd apps && npm run lint:nonogramm
    - run: cd apps && npm run build:nonogramm
      env:
        CI: true
